//! Long-Term Memory (LTM) - Persistent Storage
//!
//! Wraps existing MemoryStore for persistent storage.
//! TTL: Infinite (manual cleanup only).
//!
//! Phase 4: Will add vector index for semantic search.
//! Phase 5: Will add deduplication.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Duration;

use crate::memory::tier::{DecisionEntry, DecisionId, MemoryTier, TierError};
use crate::memory::MemoryStore;
use crate::memory::MemoryId;

/// Long-Term Memory: Persistent storage wrapper
pub struct LTM {
    store: Arc<Mutex<MemoryStore>>,
    /// Maps DecisionId to MemoryId (since MemoryEntry generates its own ID)
    id_map: HashMap<DecisionId, MemoryId>,
    
    // Phase 4: Vector index for semantic search
    // #[cfg(feature = "vector")]
    // vector_index: Option<VectorIndex>,
}

impl LTM {
    /// Create LTM wrapping an existing MemoryStore
    pub fn new(store: Arc<Mutex<MemoryStore>>) -> Self {
        Self {
            store,
            id_map: HashMap::new(),
        }
    }
    
    /// Create LTM with a fresh MemoryStore
    pub fn with_store(store: MemoryStore) -> Self {
        Self {
            store: Arc::new(Mutex::new(store)),
            id_map: HashMap::new(),
        }
    }
    
    /// Get underlying MemoryStore (for read-only access)
    pub fn inner(&self) -> Result<std::sync::MutexGuard<'_, MemoryStore>, std::sync::PoisonError<std::sync::MutexGuard<'_, MemoryStore>>> {
        self.store.lock()
    }
}

impl MemoryTier for LTM {
    fn store(&mut self, entry: DecisionEntry) -> Result<(), TierError> {
        let mut store = self.store.lock().map_err(|_| TierError::Io(std::io::Error::other("Mutex poisoned")))?;
        
        // Store the entire DecisionEntry as JSON
        let entry_json = serde_json::to_string(&entry)?;
        
        let mem_entry = crate::memory::MemoryEntry::new(entry_json, "decision")
            .with_type(crate::memory::MemoryType::Pattern);
        
        // Capture the MemoryId generated by MemoryEntry
        let memory_id = mem_entry.id.clone();
        let decision_id = entry.id.clone();
        
        store.save(mem_entry)?;
        
        // Map DecisionId to MemoryId for later retrieval
        self.id_map.insert(decision_id, memory_id);
        
        Ok(())
    }
    
    fn retrieve(&mut self, id: &DecisionId) -> Option<Arc<DecisionEntry>> {
        let store = self.store.lock().ok()?;

        // Look up MemoryId from our mapping
        let memory_id = self.id_map.get(id)?;

        store.get(memory_id).and_then(|mem_entry| {
            // Deserialize the entire DecisionEntry from stored JSON
            let entry: DecisionEntry = serde_json::from_str(&mem_entry.code).ok()?;
            Some(Arc::new(entry))
        })
    }
    
    fn promote(&mut self, _id: &DecisionId, _target: &mut dyn MemoryTier) -> Result<(), TierError> {
        // LTM is terminal - no promotion out
        Err(TierError::TerminalTier)
    }
    
    fn evict_expired(&mut self) -> Vec<DecisionId> {
        // LTM never auto-evicts
        // Manual cleanup via MemoryStore::prune() or clear()
        Vec::new()
    }
    
    fn ttl(&self) -> Duration {
        Duration::MAX // Infinite
    }
    
    fn len(&self) -> usize {
        self.store.lock().map(|s| s.count()).unwrap_or(0)
    }
    
    fn contains(&self, id: &DecisionId) -> bool {
        self.id_map.contains_key(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::memory::DecisionType;
    use tempfile::tempdir;
    
    fn make_entry() -> DecisionEntry {
        DecisionEntry::new(
            crate::memory::DecisionNode::new(DecisionType::Architectural, "test decision"),
            crate::memory::decision_log::MultiSignalScore::default(),
        )
    }
    
    #[test]
    fn test_ltm_store_and_retrieve() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("ltm.toml");
        
        let store = MemoryStore::new(Some(path)).unwrap();
        let mut ltm = LTM::with_store(store);
        
        let entry = make_entry();
        let id = entry.id.clone();
        
        ltm.store(entry).unwrap();
        assert!(ltm.contains(&id));
    }
    
    #[test]
    fn test_ltm_no_eviction() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("ltm.toml");
        
        let store = MemoryStore::new(Some(path)).unwrap();
        let mut ltm = LTM::with_store(store);
        
        let entry = make_entry();
        
        ltm.store(entry).unwrap();
        
        // Even after time passes, LTM should not auto-evict
        let evicted = ltm.evict_expired();
        assert!(evicted.is_empty());
    }
    
    #[test]
    fn test_ltm_cannot_promote() {
        let dir = tempdir().unwrap();
        let path = dir.path().join("ltm.toml");
        
        let store = MemoryStore::new(Some(path)).unwrap();
        let mut ltm = LTM::with_store(store);
        
        let entry = make_entry();
        let id = entry.id.clone();
        ltm.store(entry).unwrap();
        
        let mut stm = crate::memory::STM::new();
        
        // LTM should refuse to promote
        let result = ltm.promote(&id, &mut stm);
        assert!(result.is_err());
    }
}
